FROM node:18.16.0

WORKDIR /home/node/app
COPY ./start_script.sh .

RUN chmod 777 start_script.sh

# USER node

# Expose port 3001 for the application to listen on
EXPOSE 3001

ENTRYPOINT ["sh", "/home/node/app/start_script.sh"]
